# Generated by Django 3.0.6 on 2020-11-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0001_initial_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='default_additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
