# Generated by Django 3.0.6 on 2020-09-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0002_auto_20200908_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeassignment',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
