# Generated by Django 3.1.1 on 2020-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0002_giftexchange_assignments_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='default_allergies_sensitivities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='default_dislikes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='default_likes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
