# Generated by Django 3.1.3 on 2020-12-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0002_auto_20201112_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclink',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
