# Generated by Django 3.0.6 on 2020-10-26 14:40

from django.db import migrations, models
import giftexchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0003_exchangeassignment_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField(default=giftexchange.models.twentyfourhoursfromnow)),
                ('user_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
