# Generated by Django 3.1.1 on 2020-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0003_add_default_preference_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('invited', 'invited'), ('declined', 'declined'), ('active', 'active')], default='invited', max_length=10),
        ),
    ]
