# Generated by Django 3.0.6 on 2020-12-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0004_participant_appuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='appuser',
            new_name='_appuser',
        ),
    ]
