# Generated by Django 3.0.6 on 2020-10-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0004_magiclink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='needs_password_reset',
        ),
        migrations.AddField(
            model_name='appuser',
            name='default_shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
