# Generated by Django 3.0.6 on 2020-10-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0006_giftexchange_ship_gifts_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinvitation',
            name='invitee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='giftexchange.AppUser'),
        ),
        migrations.AlterField(
            model_name='appinvitation',
            name='invitee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
