# Generated by Django 3.0.6 on 2020-10-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0007_auto_20201026_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='appuser',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='tmp', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='tmp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='tmp', max_length=100),
            preserve_default=False,
        ),
    ]
