# Generated by Django 3.0.6 on 2020-10-27 13:04

from django.db import migrations
from giftexchange.models import Participant

def forward(apps, schema_editor):
    Participant.objects.all().delete()

def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0008_decouple_participant_from_appuser'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
