# Generated by Django 3.0.6 on 2020-10-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0009_clear_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'sent'), ('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=10)),
                ('giftexchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftexchange.GiftExchange')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftexchange.AppUser')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftexchange.Participant')),
            ],
        ),
    ]
