# Generated by Django 3.0.6 on 2020-10-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftexchange', '0010_admininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='magic_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftexchange.MagicLink'),
        ),
    ]
